-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpG2ZG5c4rxl+Q5bd
hFZ2oASgZnnfKl9btVEcabCMB+CgCgYIKoZIzj0DAQehRANCAARMCm3Avs84Qcmo
DZLANAOtKFYvSuGq+Ncc8F59s6hP0Hnew7MNSM+5/8dygARMTGzUQejie0Xl/URM
ZrIAeR60
-----END PRIVATE KEY-----